version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
    environment:
      - JUNO_HOST=proxy
      - JUNO_PORT=8080
    networks:
      - appnetwork
      - junonet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
  junonet:
    external: true
    name: ${DOCKER_NETWORK:-manifest_junonet}